/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary": "var(--color-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "error-container": "var(--color-error-container)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "on-error-container": "var(--color-on-error-container)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "tertiary": "var(--color-tertiary)",
        "outline": "var(--color-outline)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "outline-variant": "var(--color-outline-variant)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface": "var(--color-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed": "var(--color-primary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "secondary": "var(--color-secondary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "background": "var(--color-background)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-error": "var(--color-on-error)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-bright": "var(--color-surface-bright)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "error": "var(--color-error)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-background": "var(--color-on-background)",
        "surface-deep": "var(--color-surface-deep)",
        "warning-yellow": "var(--color-warning-yellow)",
        "glow": "var(--color-glow)"
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'sidebar-width': '312px',
        'nav-width': '208px',
      },
      fontFamily: {
        sans: ['Inter', 'Outfit', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'Outfit', 'sans-serif'],
        'headline-md': ['Inter', 'Outfit', 'sans-serif'],
        'title-sm': ['Inter', 'Outfit', 'sans-serif'],
        'body-base': ['Inter', 'Outfit', 'sans-serif'],
        'label-caps': ['Inter', 'Outfit', 'sans-serif'],
        'body-mono': ['JetBrains Mono', 'monospace'],
        'label-mono-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-mono': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'label-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-primary-sm': '0 0 10px rgba(var(--primary-rgb, 115, 212, 232), 0.15)',
        'glow-primary-md': '0 0 15px rgba(var(--primary-rgb, 115, 212, 232), 0.25)',
        'glow-primary-lg': '0 0 20px rgba(var(--primary-rgb, 115, 212, 232), 0.35)',
        'glow-tertiary-sm': '0 0 8px rgba(var(--tertiary-rgb, 69, 223, 164), 0.5)',
        'glow-inset': 'inset 0 0 10px rgba(var(--primary-rgb, 115, 212, 232), 0.1)',
        'glow-inset-hover': 'inset 0 0 15px rgba(var(--primary-rgb, 115, 212, 232), 0.2)',
        'card-dark': '0 0 15px rgba(0, 0, 0, 0.2)',
      }
    },
  },
  plugins: [],
}
