/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#879395",
        "outline-variant": "#3e494b",
        "background": "#10131a",
        "on-background": "#e0e2ec",
        "surface": "#10131a",
        "surface-dim": "#10131a",
        "surface-bright": "#363941",
        "surface-deep": "#0b0e15",
        "surface-container-lowest": "#0b0e15",
        "surface-container-low": "#191c22",
        "surface-container": "#1d2027",
        "surface-container-high": "#272a31",
        "surface-container-highest": "#32353c",
        "surface-variant": "#32353c",
        "surface-tint": "#73d4e8",
        "on-surface": "#e0e2ec",
        "on-surface-variant": "#bbc9cd",
        "inverse-surface": "#e0e2ec",
        "inverse-on-surface": "#2d3038",
        "primary": "#effcff",
        "on-primary": "#00363e",
        "primary-container": "#8aebff",
        "on-primary-container": "#006b7a",
        "inverse-primary": "#006877",
        "primary-fixed": "#a2eeff",
        "primary-fixed-dim": "#73d4e8",
        "on-primary-fixed": "#001f25",
        "on-primary-fixed-variant": "#004e5a",
        "secondary": "#c0c6d7",
        "on-secondary": "#2a303e",
        "secondary-container": "#404755",
        "on-secondary-container": "#afb5c6",
        "secondary-fixed": "#dce2f4",
        "secondary-fixed-dim": "#c0c6d7",
        "on-secondary-fixed": "#151c28",
        "on-secondary-fixed-variant": "#404755",
        "tertiary": "#e7ffef",
        "on-tertiary": "#003825",
        "tertiary-container": "#61f6b9",
        "on-tertiary-container": "#006f4d",
        "tertiary-fixed": "#68fcbf",
        "tertiary-fixed-dim": "#45dfa4",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "error-red": "#ffb4ab",
        "warning-yellow": "#eab308"
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'sidebar-width': '312px',
        'nav-width': '208px',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-mono': ['JetBrains Mono', 'monospace'],
        'label-mono-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-mono': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'label-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-primary-sm': '0 0 10px rgba(115, 212, 232, 0.15)',
        'glow-primary-md': '0 0 15px rgba(115, 212, 232, 0.25)',
        'glow-primary-lg': '0 0 20px rgba(115, 212, 232, 0.35)',
        'glow-tertiary-sm': '0 0 8px rgba(69, 223, 164, 0.5)',
        'glow-inset': 'inset 0 0 10px rgba(115, 212, 232, 0.1)',
        'glow-inset-hover': 'inset 0 0 15px rgba(115, 212, 232, 0.2)',
        'card-dark': '0 0 15px rgba(0, 0, 0, 0.2)',
      }
    },
  },
  plugins: [],
}
